export const STUDIOS = [
  {
    id: 1,
    name: "Studio 100m²",
    price: "4.000.000",
    pricePerHour: "4.000.000",
    rating: 4.8,
    img: "/src/assets/S+Logo.png",
    area: "100m²",
    capacity: "10-15 người",
    location: "Quận 4, TP.HCM",
    features: [
      "Ánh sáng tự nhiên + LED",
      "Thiết bị cơ bản đầy đủ",
      "Phòng thay đồ riêng",
      "WiFi tốc độ cao",
      "Điều hòa không khí",
    ],
    description: "Studio phù hợp cho chụp ảnh sản phẩm, chân dung và quay video ngắn.",
  },
  {
    id: 2,
    name: "Studio 180m²",
    price: "5.000.000",
    pricePerHour: "5.000.000",
    rating: 4.9,
    img: "/src/assets/S+Logo.png",
    area: "180m²",
    capacity: "15-25 người",
    location: "Quận 4, TP.HCM",
    features: [
      "Không gian rộng rãi",
      "Set design đa dạng",
      "Phòng xanh 3x3m",
      "Hệ thống ánh sáng chuyên nghiệp",
      "Phòng nghỉ và makeup",
    ],
    description: "Lý tưởng cho quay phim, livestream và sản xuất nội dung quy mô vừa.",
  },
  {
    id: 3,
    name: "Studio 220m²",
    price: "6.000.000",
    pricePerHour: "6.000.000",
    rating: 5.0,
    img: "/src/assets/S+Logo.png",
    area: "220m²",
    capacity: "20-30 người",
    location: "Quận 4, TP.HCM",
    features: [
      "Phòng xanh riêng biệt",
      "Hệ thống âm thanh chuyên nghiệp",
      "Nhiều góc quay",
      "Thiết bị cao cấp",
      "Hỗ trợ kỹ thuật viên",
    ],
    description: "Studio cao cấp với đầy đủ tiện nghi cho các dự án quay phim chuyên nghiệp.",
  },
  {
    id: 4,
    name: "Studio 300m²",
    price: "7.000.000",
    pricePerHour: "7.000.000",
    rating: 5.0,
    img: "/src/assets/S+Logo.png",
    area: "300m²",
    capacity: "30-50 người",
    location: "Quận 4, TP.HCM",
    features: [
      "Premium setup đầy đủ",
      "Thiết bị flagship",
      "Nhiều set design",
      "Phòng hậu kỳ riêng",
      "Dịch vụ VIP",
    ],
    description: "Studio lớn nhất với đầy đủ thiết bị và dịch vụ cao cấp cho các dự án lớn.",
  },
];

